# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _bindings
else:
    import _bindings

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


M_PI = _bindings.M_PI
M_PI_2 = _bindings.M_PI_2

def approxeq(a: "double", b: "double", epsilon: "double") -> "bool":
    return _bindings.approxeq(a, b, epsilon)

def seed_rng(seed: "uint32_t") -> "void":
    return _bindings.seed_rng(seed)

def lcg_rand() -> "uint32_t":
    return _bindings.lcg_rand()

def lcg_get_state() -> "uint32_t":
    return _bindings.lcg_get_state()

def rand_0_to_1() -> "double":
    return _bindings.rand_0_to_1()

def rand_uniform(min: "double", max: "double") -> "double":
    return _bindings.rand_uniform(min, max)

def rand_int_range(min: "int", max: "int") -> "int":
    return _bindings.rand_int_range(min, max)

def rand_int(max: "int") -> "int":
    return _bindings.rand_int(max)

def fclamp(value: "double", min: "double", max: "double") -> "double":
    return _bindings.fclamp(value, min, max)

def get_sys_time_seconds() -> "double":
    return _bindings.get_sys_time_seconds()

def sleep_ms(milliseconds: "int") -> "void":
    return _bindings.sleep_ms(milliseconds)
class Vec2D(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x: "double" = property(_bindings.Vec2D_x_get, _bindings.Vec2D_x_set)
    y: "double" = property(_bindings.Vec2D_y_get, _bindings.Vec2D_y_set)

    def __init__(self):
        _bindings.Vec2D_swiginit(self, _bindings.new_Vec2D())
    __swig_destroy__ = _bindings.delete_Vec2D

# Register Vec2D in _bindings:
_bindings.Vec2D_swigregister(Vec2D)

def vec_create(x: "double", y: "double") -> "Vec2D":
    return _bindings.vec_create(x, y)

def vec_add(v1: "Vec2D", v2: "Vec2D") -> "Vec2D":
    return _bindings.vec_add(v1, v2)

def vec_sub(v1: "Vec2D", v2: "Vec2D") -> "Vec2D":
    return _bindings.vec_sub(v1, v2)

def vec_scale(v: "Vec2D", scalar: "double") -> "Vec2D":
    return _bindings.vec_scale(v, scalar)

def vec_div(v: "Vec2D", scalar: "double") -> "Vec2D":
    return _bindings.vec_div(v, scalar)

def vec_dot(v1: "Vec2D", v2: "Vec2D") -> "double":
    return _bindings.vec_dot(v1, v2)

def vec_magnitude(v: "Vec2D") -> "double":
    return _bindings.vec_magnitude(v)

def vec_distance(v1: "Vec2D", v2: "Vec2D") -> "double":
    return _bindings.vec_distance(v1, v2)

def vec_normalize(v: "Vec2D") -> "Vec2D":
    return _bindings.vec_normalize(v)

def vec_rotate(v: "Vec2D", angle: "double") -> "Vec2D":
    return _bindings.vec_rotate(v, angle)

def vec_midpoint(v1: "Vec2D", v2: "Vec2D") -> "Vec2D":
    return _bindings.vec_midpoint(v1, v2)

def vec_approx_equal(a: "Vec2D", b: "Vec2D", epsilon: "double") -> "bool":
    return _bindings.vec_approx_equal(a, b, epsilon)

def coordinates_create(x: "double", y: "double") -> "Coordinates":
    return _bindings.coordinates_create(x, y)

def dimensions_create(width: "double", height: "double") -> "Dimensions":
    return _bindings.dimensions_create(width, height)
class LineSegment(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    start: "Coordinates" = property(_bindings.LineSegment_start_get, _bindings.LineSegment_start_set)
    end: "Coordinates" = property(_bindings.LineSegment_end_get, _bindings.LineSegment_end_set)

    def __init__(self):
        _bindings.LineSegment_swiginit(self, _bindings.new_LineSegment())
    __swig_destroy__ = _bindings.delete_LineSegment

# Register LineSegment in _bindings:
_bindings.LineSegment_swigregister(LineSegment)

def line_segment_create(start: "Vec2D", end: "Vec2D") -> "LineSegment":
    return _bindings.line_segment_create(start, end)

def line_segment_from_center(center: "Vec2D", direction: "Vec2D", length: "double") -> "LineSegment":
    return _bindings.line_segment_from_center(center, direction, length)

def line_segment_unit_vector(line: "LineSegment") -> "Vec2D":
    return _bindings.line_segment_unit_vector(line)

def meters(value: "double") -> "Meters":
    return _bindings.meters(value)

def seconds(value: "double") -> "Seconds":
    return _bindings.seconds(value)

def mps(value: "double") -> "MetersPerSecond":
    return _bindings.mps(value)

def mpss(value: "double") -> "MetersPerSecondSquared":
    return _bindings.mpss(value)

def from_feet(value: "double") -> "Meters":
    return _bindings.from_feet(value)

def to_feet(m: "Meters") -> "double":
    return _bindings.to_feet(m)

def from_miles(value: "double") -> "Meters":
    return _bindings.from_miles(value)

def to_miles(m: "Meters") -> "double":
    return _bindings.to_miles(m)

def from_kilometers(value: "double") -> "Meters":
    return _bindings.from_kilometers(value)

def to_kilometers(m: "Meters") -> "double":
    return _bindings.to_kilometers(m)

def from_inches(value: "double") -> "Meters":
    return _bindings.from_inches(value)

def to_inches(m: "Meters") -> "double":
    return _bindings.to_inches(m)

def from_centimeters(value: "double") -> "Meters":
    return _bindings.from_centimeters(value)

def to_centimeters(m: "Meters") -> "double":
    return _bindings.to_centimeters(m)

def from_millimeters(value: "double") -> "Meters":
    return _bindings.from_millimeters(value)

def to_millimeters(m: "Meters") -> "double":
    return _bindings.to_millimeters(m)

def from_kmph(value: "double") -> "MetersPerSecond":
    return _bindings.from_kmph(value)

def to_kmph(mps: "MetersPerSecond") -> "double":
    return _bindings.to_kmph(mps)

def from_mph(value: "double") -> "MetersPerSecond":
    return _bindings.from_mph(value)

def to_mph(mps: "MetersPerSecond") -> "double":
    return _bindings.to_mph(mps)

def from_fps(value: "double") -> "MetersPerSecond":
    return _bindings.from_fps(value)

def to_fps(mps: "MetersPerSecond") -> "double":
    return _bindings.to_fps(mps)
DIRECTION_CCW = _bindings.DIRECTION_CCW
DIRECTION_CW = _bindings.DIRECTION_CW
DIRECTION_EAST = _bindings.DIRECTION_EAST
DIRECTION_WEST = _bindings.DIRECTION_WEST
DIRECTION_NORTH = _bindings.DIRECTION_NORTH
DIRECTION_SOUTH = _bindings.DIRECTION_SOUTH

def direction_to_vector(direction: "Direction") -> "Vec2D":
    return _bindings.direction_to_vector(direction)

def direction_perpendicular_vector(direction: "Direction") -> "Vec2D":
    return _bindings.direction_perpendicular_vector(direction)

def direction_opposite(direction: "Direction") -> "Direction":
    return _bindings.direction_opposite(direction)
QUADRANT_TOP_RIGHT = _bindings.QUADRANT_TOP_RIGHT
QUADRANT_TOP_LEFT = _bindings.QUADRANT_TOP_LEFT
QUADRANT_BOTTOM_LEFT = _bindings.QUADRANT_BOTTOM_LEFT
QUADRANT_BOTTOM_RIGHT = _bindings.QUADRANT_BOTTOM_RIGHT
MAX_CARS_PER_LANE = _bindings.MAX_CARS_PER_LANE
MAX_NUM_ROADS = _bindings.MAX_NUM_ROADS
MAX_NUM_LANES_PER_ROAD = _bindings.MAX_NUM_LANES_PER_ROAD
MAX_NUM_INTERSECTIONS = _bindings.MAX_NUM_INTERSECTIONS
MAX_NUM_LANES_PER_INTERSECTION = _bindings.MAX_NUM_LANES_PER_INTERSECTION
MAX_NUM_LANES = _bindings.MAX_NUM_LANES
LANE_DEGRADATIONS_BUCKETS = _bindings.LANE_DEGRADATIONS_BUCKETS
GREEN_DURATION = _bindings.GREEN_DURATION
YELLOW_DURATION = _bindings.YELLOW_DURATION
MINOR_RED_EXTENSION = _bindings.MINOR_RED_EXTENSION
ID_NULL = _bindings.ID_NULL

def sim_get_car(sim: "Simulation", id: "CarId") -> "Car *":
    return _bindings.sim_get_car(sim, id)

def car_get_lane_progress(_self: "Car") -> "double":
    return _bindings.car_get_lane_progress(_self)

def car_get_id(_self: "Car") -> "CarId":
    return _bindings.car_get_id(_self)

def car_get_lane_rank(_self: "Car") -> "int":
    return _bindings.car_get_lane_rank(_self)

def car_set_lane_rank(_self: "Car", rank: "int") -> "void":
    return _bindings.car_set_lane_rank(_self, rank)
class Degradations(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    values: "double [5]" = property(_bindings.Degradations_values_get, _bindings.Degradations_values_set)

    def __init__(self):
        _bindings.Degradations_swiginit(self, _bindings.new_Degradations())
    __swig_destroy__ = _bindings.delete_Degradations

# Register Degradations in _bindings:
_bindings.Degradations_swigregister(Degradations)
LINEAR_LANE = _bindings.LINEAR_LANE
QUARTER_ARC_LANE = _bindings.QUARTER_ARC_LANE
class Lane(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id: "LaneId" = property(_bindings.Lane_id_get, _bindings.Lane_id_set)
    type: "LaneType" = property(_bindings.Lane_type_get, _bindings.Lane_type_set)
    name: "char [64]" = property(_bindings.Lane_name_get, _bindings.Lane_name_set)
    direction: "Direction" = property(_bindings.Lane_direction_get, _bindings.Lane_direction_set)
    width: "Meters" = property(_bindings.Lane_width_get, _bindings.Lane_width_set)
    speed_limit: "MetersPerSecond" = property(_bindings.Lane_speed_limit_get, _bindings.Lane_speed_limit_set)
    grip: "double" = property(_bindings.Lane_grip_get, _bindings.Lane_grip_set)
    degradations: "Degradations" = property(_bindings.Lane_degradations_get, _bindings.Lane_degradations_set)
    connections_incoming: "LaneId [3]" = property(_bindings.Lane_connections_incoming_get, _bindings.Lane_connections_incoming_set)
    connections: "LaneId [3]" = property(_bindings.Lane_connections_get, _bindings.Lane_connections_set)
    adjacents: "LaneId [2]" = property(_bindings.Lane_adjacents_get, _bindings.Lane_adjacents_set)
    merges_into_id: "LaneId" = property(_bindings.Lane_merges_into_id_get, _bindings.Lane_merges_into_id_set)
    merges_into_start: "double" = property(_bindings.Lane_merges_into_start_get, _bindings.Lane_merges_into_start_set)
    merges_into_end: "double" = property(_bindings.Lane_merges_into_end_get, _bindings.Lane_merges_into_end_set)
    exit_lane_id: "LaneId" = property(_bindings.Lane_exit_lane_id_get, _bindings.Lane_exit_lane_id_set)
    exit_lane_start: "double" = property(_bindings.Lane_exit_lane_start_get, _bindings.Lane_exit_lane_start_set)
    exit_lane_end: "double" = property(_bindings.Lane_exit_lane_end_get, _bindings.Lane_exit_lane_end_set)
    start_point: "Coordinates" = property(_bindings.Lane_start_point_get, _bindings.Lane_start_point_set)
    end_point: "Coordinates" = property(_bindings.Lane_end_point_get, _bindings.Lane_end_point_set)
    mid_point: "Coordinates" = property(_bindings.Lane_mid_point_get, _bindings.Lane_mid_point_set)
    center: "Coordinates" = property(_bindings.Lane_center_get, _bindings.Lane_center_set)
    length: "Meters" = property(_bindings.Lane_length_get, _bindings.Lane_length_set)
    radius: "Meters" = property(_bindings.Lane_radius_get, _bindings.Lane_radius_set)
    start_angle: "Radians" = property(_bindings.Lane_start_angle_get, _bindings.Lane_start_angle_set)
    end_angle: "Radians" = property(_bindings.Lane_end_angle_get, _bindings.Lane_end_angle_set)
    quadrant: "Quadrant" = property(_bindings.Lane_quadrant_get, _bindings.Lane_quadrant_set)
    road_id: "RoadId" = property(_bindings.Lane_road_id_get, _bindings.Lane_road_id_set)
    intersection_id: "IntersectionId" = property(_bindings.Lane_intersection_id_get, _bindings.Lane_intersection_id_set)
    is_at_intersection: "bool" = property(_bindings.Lane_is_at_intersection_get, _bindings.Lane_is_at_intersection_set)
    cars_ids: "CarId [64]" = property(_bindings.Lane_cars_ids_get, _bindings.Lane_cars_ids_set)
    num_cars: "int" = property(_bindings.Lane_num_cars_get, _bindings.Lane_num_cars_set)

    def __init__(self):
        _bindings.Lane_swiginit(self, _bindings.new_Lane())
    __swig_destroy__ = _bindings.delete_Lane

# Register Lane in _bindings:
_bindings.Lane_swigregister(Lane)
cvar = _bindings.cvar
DEGRADATIONS_ZERO = cvar.DEGRADATIONS_ZERO


def lane_set_connection_incoming_left(_self: "Lane", lane: "Lane") -> "void":
    return _bindings.lane_set_connection_incoming_left(_self, lane)

def lane_set_connection_incoming_straight(_self: "Lane", lane: "Lane") -> "void":
    return _bindings.lane_set_connection_incoming_straight(_self, lane)

def lane_set_connection_incoming_right(_self: "Lane", lane: "Lane") -> "void":
    return _bindings.lane_set_connection_incoming_right(_self, lane)

def lane_set_connection_left(_self: "Lane", lane: "Lane") -> "void":
    return _bindings.lane_set_connection_left(_self, lane)

def lane_set_connection_straight(_self: "Lane", lane: "Lane") -> "void":
    return _bindings.lane_set_connection_straight(_self, lane)

def lane_set_connection_right(_self: "Lane", lane: "Lane") -> "void":
    return _bindings.lane_set_connection_right(_self, lane)

def lane_set_adjacents(_self: "Lane", left: "Lane", right: "Lane") -> "void":
    return _bindings.lane_set_adjacents(_self, left, right)

def lane_set_adjacent_left(_self: "Lane", left: "Lane") -> "void":
    return _bindings.lane_set_adjacent_left(_self, left)

def lane_set_adjacent_right(_self: "Lane", right: "Lane") -> "void":
    return _bindings.lane_set_adjacent_right(_self, right)

def lane_set_merges_into(_self: "Lane", lane: "Lane", start: "double", end: "double") -> "void":
    return _bindings.lane_set_merges_into(_self, lane, start, end)

def lane_set_exit_lane(_self: "Lane", lane: "Lane", start: "double", end: "double") -> "void":
    return _bindings.lane_set_exit_lane(_self, lane, start, end)

def lane_set_speed_limit(_self: "Lane", speed_limit: "MetersPerSecond") -> "void":
    return _bindings.lane_set_speed_limit(_self, speed_limit)

def lane_set_grip(_self: "Lane", grip: "double") -> "void":
    return _bindings.lane_set_grip(_self, grip)

def lane_set_degradations(_self: "Lane", degradations: "Degradations") -> "void":
    return _bindings.lane_set_degradations(_self, degradations)

def lane_set_road(_self: "Lane", road: "Road") -> "void":
    return _bindings.lane_set_road(_self, road)

def lane_set_intersection(_self: "Lane", intersection: "Intersection") -> "void":
    return _bindings.lane_set_intersection(_self, intersection)

def lane_set_name(_self: "Lane", name: "char const *") -> "void":
    return _bindings.lane_set_name(_self, name)

def lane_add_car(_self: "Lane", car: "Car", sim: "Simulation") -> "void":
    return _bindings.lane_add_car(_self, car, sim)

def lane_remove_car(_self: "Lane", car: "Car", sim: "Simulation") -> "void":
    return _bindings.lane_remove_car(_self, car, sim)

def lane_move_car(_self: "Lane", car: "Car", sim: "Simulation") -> "void":
    return _bindings.lane_move_car(_self, car, sim)

def lane_get_id(_self: "Lane") -> "int":
    return _bindings.lane_get_id(_self)

def lane_get_type(_self: "Lane") -> "LaneType":
    return _bindings.lane_get_type(_self)

def lane_get_direction(_self: "Lane") -> "Direction":
    return _bindings.lane_get_direction(_self)

def lane_get_width(_self: "Lane") -> "Meters":
    return _bindings.lane_get_width(_self)

def lane_get_speed_limit(_self: "Lane") -> "MetersPerSecond":
    return _bindings.lane_get_speed_limit(_self)

def lane_get_grip(_self: "Lane") -> "double":
    return _bindings.lane_get_grip(_self)

def lane_get_start_point(_self: "Lane") -> "Coordinates":
    return _bindings.lane_get_start_point(_self)

def lane_get_mid_point(_self: "Lane") -> "Coordinates":
    return _bindings.lane_get_mid_point(_self)

def lane_get_end_point(_self: "Lane") -> "Coordinates":
    return _bindings.lane_get_end_point(_self)

def lane_get_center(_self: "Lane") -> "Coordinates":
    return _bindings.lane_get_center(_self)

def lane_get_length(_self: "Lane") -> "Meters":
    return _bindings.lane_get_length(_self)

def lane_get_degradations(_self: "Lane") -> "Degradations":
    return _bindings.lane_get_degradations(_self)

def lane_get_connection_incoming_left_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_connection_incoming_left_id(_self)

def lane_get_connection_incoming_left(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_connection_incoming_left(_self, map)

def lane_get_connection_incoming_straight_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_connection_incoming_straight_id(_self)

def lane_get_connection_incoming_straight(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_connection_incoming_straight(_self, map)

def lane_get_connection_incoming_right_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_connection_incoming_right_id(_self)

def lane_get_connection_incoming_right(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_connection_incoming_right(_self, map)

def lane_get_connection_left_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_connection_left_id(_self)

def lane_get_connection_left(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_connection_left(_self, map)

def lane_get_connection_straight_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_connection_straight_id(_self)

def lane_get_connection_straight(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_connection_straight(_self, map)

def lane_get_connection_right_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_connection_right_id(_self)

def lane_get_connection_right(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_connection_right(_self, map)

def lane_get_merge_into_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_merge_into_id(_self)

def lane_get_merge_into(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_merge_into(_self, map)

def lane_get_exit_lane_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_exit_lane_id(_self)

def lane_get_exit_lane(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_exit_lane(_self, map)

def lane_get_adjacent_left_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_adjacent_left_id(_self)

def lane_get_adjacent_left(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_adjacent_left(_self, map)

def lane_get_adjacent_right_id(_self: "Lane") -> "LaneId":
    return _bindings.lane_get_adjacent_right_id(_self)

def lane_get_adjacent_right(_self: "Lane", map: "Map") -> "Lane *":
    return _bindings.lane_get_adjacent_right(_self, map)

def lane_get_road_id(_self: "Lane") -> "RoadId":
    return _bindings.lane_get_road_id(_self)

def lane_get_road(_self: "Lane", map: "Map") -> "Road *":
    return _bindings.lane_get_road(_self, map)

def lane_get_intersection_id(_self: "Lane") -> "IntersectionId":
    return _bindings.lane_get_intersection_id(_self)

def lane_is_at_intersection(_self: "Lane") -> "bool":
    return _bindings.lane_is_at_intersection(_self)

def lane_get_intersection(_self: "Lane", map: "Map") -> "Intersection *":
    return _bindings.lane_get_intersection(_self, map)

def lane_get_num_cars(_self: "Lane") -> "int":
    return _bindings.lane_get_num_cars(_self)

def lane_get_car_id(_self: "Lane", index: "int") -> "CarId":
    return _bindings.lane_get_car_id(_self, index)

def lane_get_car(_self: "Lane", sim: "Simulation", index: "int") -> "Car *":
    return _bindings.lane_get_car(_self, sim, index)

def lane_get_num_connections_incoming(_self: "Lane") -> "int":
    return _bindings.lane_get_num_connections_incoming(_self)

def lane_get_num_connections(_self: "Lane") -> "int":
    return _bindings.lane_get_num_connections(_self)

def lane_is_merge_available(_self: "Lane") -> "bool":
    return _bindings.lane_is_merge_available(_self)

def lane_is_exit_lane_available(_self: "Lane", progress: "double") -> "bool":
    return _bindings.lane_is_exit_lane_available(_self, progress)

def lane_is_exit_lane_eventually_available(_self: "Lane", progress: "double") -> "bool":
    return _bindings.lane_is_exit_lane_eventually_available(_self, progress)

def lane_create(map: "Map", type: "LaneType", direction: "Direction", width: "Meters", speed_limit: "MetersPerSecond", grip: "double", degradations: "Degradations") -> "Lane *":
    return _bindings.lane_create(map, type, direction, width, speed_limit, grip, degradations)

def linear_lane_create_from_center_dir_len(map: "Map", center: "Vec2D", direction: "Direction", length: "Meters", width: "Meters", speed_limit: "MetersPerSecond", grip: "double", degradations: "Degradations") -> "Lane *":
    return _bindings.linear_lane_create_from_center_dir_len(map, center, direction, length, width, speed_limit, grip, degradations)

def linear_lane_create_from_start_end(map: "Map", start: "Vec2D", end: "Vec2D", width: "Meters", speed_limit: "MetersPerSecond", grip: "double", degradations: "Degradations") -> "Lane *":
    return _bindings.linear_lane_create_from_start_end(map, start, end, width, speed_limit, grip, degradations)

def quarter_arc_lane_create_from_start_end(map: "Map", start_point: "Vec2D", end_point: "Vec2D", direction: "Direction", width: "Meters", speed_limit: "MetersPerSecond", grip: "double", degradations: "Degradations") -> "Lane *":
    return _bindings.quarter_arc_lane_create_from_start_end(map, start_point, end_point, direction, width, speed_limit, grip, degradations)
STRAIGHT = _bindings.STRAIGHT
TURN = _bindings.TURN
class Road(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id: "int" = property(_bindings.Road_id_get, _bindings.Road_id_set)
    type: "RoadType" = property(_bindings.Road_type_get, _bindings.Road_type_set)
    name: "char [64]" = property(_bindings.Road_name_get, _bindings.Road_name_set)
    lane_ids: "LaneId [4]" = property(_bindings.Road_lane_ids_get, _bindings.Road_lane_ids_set)
    num_lanes: "int" = property(_bindings.Road_num_lanes_get, _bindings.Road_num_lanes_set)
    speed_limit: "MetersPerSecond" = property(_bindings.Road_speed_limit_get, _bindings.Road_speed_limit_set)
    grip: "double" = property(_bindings.Road_grip_get, _bindings.Road_grip_set)
    lane_width: "Meters" = property(_bindings.Road_lane_width_get, _bindings.Road_lane_width_set)
    direction: "Direction" = property(_bindings.Road_direction_get, _bindings.Road_direction_set)
    length: "Meters" = property(_bindings.Road_length_get, _bindings.Road_length_set)
    width: "Meters" = property(_bindings.Road_width_get, _bindings.Road_width_set)
    start_point: "Coordinates" = property(_bindings.Road_start_point_get, _bindings.Road_start_point_set)
    end_point: "Coordinates" = property(_bindings.Road_end_point_get, _bindings.Road_end_point_set)
    mid_point: "Coordinates" = property(_bindings.Road_mid_point_get, _bindings.Road_mid_point_set)
    center: "Coordinates" = property(_bindings.Road_center_get, _bindings.Road_center_set)
    radius: "Meters" = property(_bindings.Road_radius_get, _bindings.Road_radius_set)
    start_angle: "Radians" = property(_bindings.Road_start_angle_get, _bindings.Road_start_angle_set)
    end_angle: "Radians" = property(_bindings.Road_end_angle_get, _bindings.Road_end_angle_set)
    quadrant: "Quadrant" = property(_bindings.Road_quadrant_get, _bindings.Road_quadrant_set)
    road_from_id: "RoadId" = property(_bindings.Road_road_from_id_get, _bindings.Road_road_from_id_set)
    road_to_id: "RoadId" = property(_bindings.Road_road_to_id_get, _bindings.Road_road_to_id_set)

    def __init__(self):
        _bindings.Road_swiginit(self, _bindings.new_Road())
    __swig_destroy__ = _bindings.delete_Road

# Register Road in _bindings:
_bindings.Road_swigregister(Road)

def road_set_name(_self: "Road", name: "char const *") -> "void":
    return _bindings.road_set_name(_self, name)

def road_set_speed_limit(_self: "Road", speed_limit: "MetersPerSecond") -> "void":
    return _bindings.road_set_speed_limit(_self, speed_limit)

def road_set_grip(_self: "Road", grip: "double") -> "void":
    return _bindings.road_set_grip(_self, grip)

def road_get_id(_self: "Road") -> "int":
    return _bindings.road_get_id(_self)

def road_get_type(_self: "Road") -> "RoadType":
    return _bindings.road_get_type(_self)

def road_get_name(_self: "Road") -> "char const *":
    return _bindings.road_get_name(_self)

def road_get_num_lanes(_self: "Road") -> "int":
    return _bindings.road_get_num_lanes(_self)

def road_get_speed_limit(_self: "Road") -> "MetersPerSecond":
    return _bindings.road_get_speed_limit(_self)

def road_get_grip(_self: "Road") -> "double":
    return _bindings.road_get_grip(_self)

def road_get_lane_width(_self: "Road") -> "Meters":
    return _bindings.road_get_lane_width(_self)

def road_get_direction(_self: "Road") -> "Direction":
    return _bindings.road_get_direction(_self)

def road_get_length(_self: "Road") -> "Meters":
    return _bindings.road_get_length(_self)

def road_get_width(_self: "Road") -> "Meters":
    return _bindings.road_get_width(_self)

def road_get_start_point(_self: "Road") -> "Coordinates":
    return _bindings.road_get_start_point(_self)

def road_get_end_point(_self: "Road") -> "Coordinates":
    return _bindings.road_get_end_point(_self)

def road_get_mid_point(_self: "Road") -> "Coordinates":
    return _bindings.road_get_mid_point(_self)

def road_get_center(_self: "Road") -> "Coordinates":
    return _bindings.road_get_center(_self)

def road_get_lane(_self: "Road", map: "Map", index: "int") -> "Lane *":
    return _bindings.road_get_lane(_self, map, index)

def road_get_leftmost_lane(_self: "Road", map: "Map") -> "Lane *":
    return _bindings.road_get_leftmost_lane(_self, map)

def road_get_rightmost_lane(_self: "Road", map: "Map") -> "Lane *":
    return _bindings.road_get_rightmost_lane(_self, map)

def road_is_merge_available(_self: "Road", map: "Map") -> "bool":
    return _bindings.road_is_merge_available(_self, map)

def road_is_exit_road_available(_self: "Road", map: "Map", progress: "double") -> "bool":
    return _bindings.road_is_exit_road_available(_self, map, progress)

def road_is_exit_road_eventually_available(_self: "Road", map: "Map", progress: "double") -> "bool":
    return _bindings.road_is_exit_road_eventually_available(_self, map, progress)

def turn_road_get_from(_self: "Road", map: "Map") -> "Road *":
    return _bindings.turn_road_get_from(_self, map)

def turn_road_get_to(_self: "Road", map: "Map") -> "Road *":
    return _bindings.turn_road_get_to(_self, map)

def straight_road_create_from_center_dir_len(map: "Map", center: "Vec2D", direction: "Direction", length: "Meters", num_lanes: "int", lane_width: "Meters", speed_limit: "MetersPerSecond", grip: "double") -> "Road *":
    return _bindings.straight_road_create_from_center_dir_len(map, center, direction, length, num_lanes, lane_width, speed_limit, grip)

def straight_road_create_from_start_end(map: "Map", start: "Vec2D", end: "Vec2D", num_lanes: "int", lane_width: "Meters", speed_limit: "MetersPerSecond", grip: "double") -> "Road *":
    return _bindings.straight_road_create_from_start_end(map, start, end, num_lanes, lane_width, speed_limit, grip)

def straight_road_make_opposite(map: "Map", road: "Road") -> "Road *":
    return _bindings.straight_road_make_opposite(map, road)

def straight_road_make_opposite_and_update_adjacents(map: "Map", road: "Road") -> "Road *":
    return _bindings.straight_road_make_opposite_and_update_adjacents(map, road)

def straight_road_split_at_and_update_connections(road: "Road", map: "Map", position: "Meters", gap: "Meters") -> "Road *":
    return _bindings.straight_road_split_at_and_update_connections(road, map, position, gap)

def turn_create_and_set_connections_and_adjacents(map: "Map", road_from: "Road", road_to: "Road", direction: "Direction", speed_limit: "MetersPerSecond", grip: "double", opposite_turn: "Road") -> "Road *":
    return _bindings.turn_create_and_set_connections_and_adjacents(map, road_from, road_to, direction, speed_limit, grip, opposite_turn)
NS_GREEN_EW_RED = _bindings.NS_GREEN_EW_RED
NS_YELLOW_EW_RED = _bindings.NS_YELLOW_EW_RED
ALL_RED_BEFORE_EW_GREEN = _bindings.ALL_RED_BEFORE_EW_GREEN
NS_RED_EW_GREEN = _bindings.NS_RED_EW_GREEN
EW_YELLOW_NS_RED = _bindings.EW_YELLOW_NS_RED
ALL_RED_BEFORE_NS_GREEN = _bindings.ALL_RED_BEFORE_NS_GREEN
FOUR_WAY_STOP = _bindings.FOUR_WAY_STOP
NUM_TRAFFIC_CONTROL_STATES = _bindings.NUM_TRAFFIC_CONTROL_STATES
class Intersection(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id: "IntersectionId" = property(_bindings.Intersection_id_get, _bindings.Intersection_id_set)
    name: "char [64]" = property(_bindings.Intersection_name_get, _bindings.Intersection_name_set)
    lane_ids: "LaneId [32]" = property(_bindings.Intersection_lane_ids_get, _bindings.Intersection_lane_ids_set)
    num_lanes: "int" = property(_bindings.Intersection_num_lanes_get, _bindings.Intersection_num_lanes_set)
    lane_width: "Meters" = property(_bindings.Intersection_lane_width_get, _bindings.Intersection_lane_width_set)
    speed_limit: "MetersPerSecond" = property(_bindings.Intersection_speed_limit_get, _bindings.Intersection_speed_limit_set)
    grip: "double" = property(_bindings.Intersection_grip_get, _bindings.Intersection_grip_set)
    center: "Coordinates" = property(_bindings.Intersection_center_get, _bindings.Intersection_center_set)
    dimensions: "Dimensions" = property(_bindings.Intersection_dimensions_get, _bindings.Intersection_dimensions_set)
    road_eastbound_from_id: "RoadId" = property(_bindings.Intersection_road_eastbound_from_id_get, _bindings.Intersection_road_eastbound_from_id_set)
    road_eastbound_to_id: "RoadId" = property(_bindings.Intersection_road_eastbound_to_id_get, _bindings.Intersection_road_eastbound_to_id_set)
    road_westbound_from_id: "RoadId" = property(_bindings.Intersection_road_westbound_from_id_get, _bindings.Intersection_road_westbound_from_id_set)
    road_westbound_to_id: "RoadId" = property(_bindings.Intersection_road_westbound_to_id_get, _bindings.Intersection_road_westbound_to_id_set)
    road_northbound_from_id: "RoadId" = property(_bindings.Intersection_road_northbound_from_id_get, _bindings.Intersection_road_northbound_from_id_set)
    road_northbound_to_id: "RoadId" = property(_bindings.Intersection_road_northbound_to_id_get, _bindings.Intersection_road_northbound_to_id_set)
    road_southbound_from_id: "RoadId" = property(_bindings.Intersection_road_southbound_from_id_get, _bindings.Intersection_road_southbound_from_id_set)
    road_southbound_to_id: "RoadId" = property(_bindings.Intersection_road_southbound_to_id_get, _bindings.Intersection_road_southbound_to_id_set)
    turn_radius: "Meters" = property(_bindings.Intersection_turn_radius_get, _bindings.Intersection_turn_radius_set)
    left_lane_turns_left_only: "bool" = property(_bindings.Intersection_left_lane_turns_left_only_get, _bindings.Intersection_left_lane_turns_left_only_set)
    right_lane_turns_right_only: "bool" = property(_bindings.Intersection_right_lane_turns_right_only_get, _bindings.Intersection_right_lane_turns_right_only_set)
    state: "IntersectionState" = property(_bindings.Intersection_state_get, _bindings.Intersection_state_set)
    countdown: "Seconds" = property(_bindings.Intersection_countdown_get, _bindings.Intersection_countdown_set)

    def __init__(self):
        _bindings.Intersection_swiginit(self, _bindings.new_Intersection())
    __swig_destroy__ = _bindings.delete_Intersection

# Register Intersection in _bindings:
_bindings.Intersection_swigregister(Intersection)
TRAFFIC_STATE_DURATIONS = cvar.TRAFFIC_STATE_DURATIONS


def intersection_set_name(_self: "Intersection", name: "char const *") -> "void":
    return _bindings.intersection_set_name(_self, name)

def intersection_set_speed_limit(_self: "Intersection", speed_limit: "MetersPerSecond") -> "void":
    return _bindings.intersection_set_speed_limit(_self, speed_limit)

def intersection_set_grip(_self: "Intersection", grip: "double") -> "void":
    return _bindings.intersection_set_grip(_self, grip)

def intersection_get_id(_self: "Intersection") -> "int":
    return _bindings.intersection_get_id(_self)

def intersection_get_name(_self: "Intersection") -> "char const *":
    return _bindings.intersection_get_name(_self)

def intersection_get_num_lanes(_self: "Intersection") -> "int":
    return _bindings.intersection_get_num_lanes(_self)

def intersection_get_center(_self: "Intersection") -> "Coordinates":
    return _bindings.intersection_get_center(_self)

def intersection_get_state(_self: "Intersection") -> "IntersectionState":
    return _bindings.intersection_get_state(_self)

def intersection_get_countdown(_self: "Intersection") -> "Seconds":
    return _bindings.intersection_get_countdown(_self)

def intersection_get_left_lane_turns_left_only(_self: "Intersection") -> "bool":
    return _bindings.intersection_get_left_lane_turns_left_only(_self)

def intersection_get_right_lane_turns_right_only(_self: "Intersection") -> "bool":
    return _bindings.intersection_get_right_lane_turns_right_only(_self)

def intersection_get_turn_radius(_self: "Intersection") -> "Meters":
    return _bindings.intersection_get_turn_radius(_self)

def intersection_get_dimensions(_self: "Intersection") -> "Dimensions":
    return _bindings.intersection_get_dimensions(_self)

def intersection_get_lane(_self: "Intersection", map: "Map", index: "int") -> "Lane *":
    return _bindings.intersection_get_lane(_self, map, index)

def intersection_get_road_eastbound_from(_self: "Intersection", map: "Map") -> "Road *":
    return _bindings.intersection_get_road_eastbound_from(_self, map)

def intersection_get_road_eastbound_to(_self: "Intersection", map: "Map") -> "Road *":
    return _bindings.intersection_get_road_eastbound_to(_self, map)

def intersection_get_road_westbound_from(_self: "Intersection", map: "Map") -> "Road *":
    return _bindings.intersection_get_road_westbound_from(_self, map)

def intersection_get_road_westbound_to(_self: "Intersection", map: "Map") -> "Road *":
    return _bindings.intersection_get_road_westbound_to(_self, map)

def intersection_get_road_northbound_from(_self: "Intersection", map: "Map") -> "Road *":
    return _bindings.intersection_get_road_northbound_from(_self, map)

def intersection_get_road_northbound_to(_self: "Intersection", map: "Map") -> "Road *":
    return _bindings.intersection_get_road_northbound_to(_self, map)

def intersection_get_road_southbound_from(_self: "Intersection", map: "Map") -> "Road *":
    return _bindings.intersection_get_road_southbound_from(_self, map)

def intersection_get_road_southbound_to(_self: "Intersection", map: "Map") -> "Road *":
    return _bindings.intersection_get_road_southbound_to(_self, map)

def intersection_create_and_form_connections(map: "Map", road_eastbound_from: "Road", road_eastbound_to: "Road", road_westbound_from: "Road", road_westbound_to: "Road", road_northbound_from: "Road", road_northbound_to: "Road", road_southbound_from: "Road", road_southbound_to: "Road", is_four_way_stop: "bool", left_lane_turns_left_only: "bool", right_lane_turns_right_only: "bool", speed_limit: "MetersPerSecond", grip: "double") -> "Intersection *":
    return _bindings.intersection_create_and_form_connections(map, road_eastbound_from, road_eastbound_to, road_westbound_from, road_westbound_to, road_northbound_from, road_northbound_to, road_southbound_from, road_southbound_to, is_four_way_stop, left_lane_turns_left_only, right_lane_turns_right_only, speed_limit, grip)

def intersection_create_from_crossing_roads_and_update_connections(map: "Map", eastbound: "Road", westbound: "Road", northbound: "Road", southbound: "Road", is_four_way_stop: "bool", turn_radius: "Meters", left_lane_turns_left_only: "bool", right_lane_turns_right_only: "bool", speed_limit: "MetersPerSecond", grip: "double") -> "Intersection *":
    return _bindings.intersection_create_from_crossing_roads_and_update_connections(map, eastbound, westbound, northbound, southbound, is_four_way_stop, turn_radius, left_lane_turns_left_only, right_lane_turns_right_only, speed_limit, grip)

def intersection_update(_self: "Intersection", dt: "Seconds") -> "void":
    return _bindings.intersection_update(_self, dt)

def print_traffic_state(intersection: "Intersection") -> "void":
    return _bindings.print_traffic_state(intersection)

def road_leads_to_intersection(road: "Road", map: "Map") -> "Intersection *":
    return _bindings.road_leads_to_intersection(road, map)

def road_comes_from_intersection(road: "Road", map: "Map") -> "Intersection *":
    return _bindings.road_comes_from_intersection(road, map)
class Map(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lanes: "Lane [350]" = property(_bindings.Map_lanes_get, _bindings.Map_lanes_set)
    roads: "Road [128]" = property(_bindings.Map_roads_get, _bindings.Map_roads_set)
    intersections: "Intersection [10]" = property(_bindings.Map_intersections_get, _bindings.Map_intersections_set)
    num_lanes: "int" = property(_bindings.Map_num_lanes_get, _bindings.Map_num_lanes_set)
    num_roads: "int" = property(_bindings.Map_num_roads_get, _bindings.Map_num_roads_set)
    num_intersections: "int" = property(_bindings.Map_num_intersections_get, _bindings.Map_num_intersections_set)

    def __init__(self):
        _bindings.Map_swiginit(self, _bindings.new_Map())
    __swig_destroy__ = _bindings.delete_Map

# Register Map in _bindings:
_bindings.Map_swigregister(Map)

def map_init(_self: "Map") -> "void":
    return _bindings.map_init(_self)

def map_get_new_lane(_self: "Map") -> "Lane *":
    return _bindings.map_get_new_lane(_self)

def map_get_new_road(_self: "Map") -> "Road *":
    return _bindings.map_get_new_road(_self)

def map_get_new_intersection(_self: "Map") -> "Intersection *":
    return _bindings.map_get_new_intersection(_self)

def map_get_lane(_self: "Map", id: "LaneId") -> "Lane *":
    return _bindings.map_get_lane(_self, id)

def map_get_road(_self: "Map", id: "RoadId") -> "Road *":
    return _bindings.map_get_road(_self, id)

def map_get_road_by_lane_id(_self: "Map", id: "LaneId") -> "Road *":
    return _bindings.map_get_road_by_lane_id(_self, id)

def map_get_intersection(_self: "Map", id: "IntersectionId") -> "Intersection *":
    return _bindings.map_get_intersection(_self, id)

def map_get_intersection_by_lane_id(_self: "Map", id: "LaneId") -> "Intersection *":
    return _bindings.map_get_intersection_by_lane_id(_self, id)

def map_get_lane_by_name(_self: "Map", name: "char const *") -> "Lane *":
    return _bindings.map_get_lane_by_name(_self, name)

def map_get_road_by_name(_self: "Map", name: "char const *") -> "Road *":
    return _bindings.map_get_road_by_name(_self, name)

def map_get_intersection_by_name(_self: "Map", name: "char const *") -> "Intersection *":
    return _bindings.map_get_intersection_by_name(_self, name)

def map_get_lanes(_self: "Map") -> "Lane *":
    return _bindings.map_get_lanes(_self)

def map_get_num_lanes(_self: "Map") -> "int":
    return _bindings.map_get_num_lanes(_self)

def map_get_roads(_self: "Map") -> "Road *":
    return _bindings.map_get_roads(_self)

def map_get_num_roads(_self: "Map") -> "int":
    return _bindings.map_get_num_roads(_self)

def map_get_intersections(_self: "Map") -> "Intersection *":
    return _bindings.map_get_intersections(_self)

def map_get_num_intersections(_self: "Map") -> "int":
    return _bindings.map_get_num_intersections(_self)
class CarAccelProfile(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    max_acceleration: "MetersPerSecondSquared" = property(_bindings.CarAccelProfile_max_acceleration_get, _bindings.CarAccelProfile_max_acceleration_set)
    max_acceleration_reverse_gear: "MetersPerSecondSquared" = property(_bindings.CarAccelProfile_max_acceleration_reverse_gear_get, _bindings.CarAccelProfile_max_acceleration_reverse_gear_set)
    max_deceleration: "MetersPerSecondSquared" = property(_bindings.CarAccelProfile_max_deceleration_get, _bindings.CarAccelProfile_max_deceleration_set)

    def __init__(self):
        _bindings.CarAccelProfile_swiginit(self, _bindings.new_CarAccelProfile())
    __swig_destroy__ = _bindings.delete_CarAccelProfile

# Register CarAccelProfile in _bindings:
_bindings.CarAccelProfile_swigregister(CarAccelProfile)

def car_accel_profile_get_effective(capable: "CarAccelProfile", preferred: "CarAccelProfile") -> "CarAccelProfile":
    return _bindings.car_accel_profile_get_effective(capable, preferred)
class CarCapabilities(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    accel_profile: "CarAccelProfile" = property(_bindings.CarCapabilities_accel_profile_get, _bindings.CarCapabilities_accel_profile_set)
    top_speed: "MetersPerSecond" = property(_bindings.CarCapabilities_top_speed_get, _bindings.CarCapabilities_top_speed_set)
    reaction_time_delay: "Seconds" = property(_bindings.CarCapabilities_reaction_time_delay_get, _bindings.CarCapabilities_reaction_time_delay_set)

    def __init__(self):
        _bindings.CarCapabilities_swiginit(self, _bindings.new_CarCapabilities())
    __swig_destroy__ = _bindings.delete_CarCapabilities

# Register CarCapabilities in _bindings:
_bindings.CarCapabilities_swigregister(CarCapabilities)
INDICATOR_LEFT = _bindings.INDICATOR_LEFT
INDICATOR_NONE = _bindings.INDICATOR_NONE
INDICATOR_RIGHT = _bindings.INDICATOR_RIGHT
class CarPersonality(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lane: "int" = property(_bindings.CarPersonality_lane_get, _bindings.CarPersonality_lane_set)
    turn_speed: "MetersPerSecond" = property(_bindings.CarPersonality_turn_speed_get, _bindings.CarPersonality_turn_speed_set)
    scenic: "double" = property(_bindings.CarPersonality_scenic_get, _bindings.CarPersonality_scenic_set)
    distance_to_front_vehicle: "Meters" = property(_bindings.CarPersonality_distance_to_front_vehicle_get, _bindings.CarPersonality_distance_to_front_vehicle_set)
    distance_to_back_vehicle: "Meters" = property(_bindings.CarPersonality_distance_to_back_vehicle_get, _bindings.CarPersonality_distance_to_back_vehicle_set)
    run_yellow_light: "bool" = property(_bindings.CarPersonality_run_yellow_light_get, _bindings.CarPersonality_run_yellow_light_set)
    turn_right_on_red: "bool" = property(_bindings.CarPersonality_turn_right_on_red_get, _bindings.CarPersonality_turn_right_on_red_set)
    aversion_to_rough_terrain: "double" = property(_bindings.CarPersonality_aversion_to_rough_terrain_get, _bindings.CarPersonality_aversion_to_rough_terrain_set)
    aversion_to_traffic_jam: "double" = property(_bindings.CarPersonality_aversion_to_traffic_jam_get, _bindings.CarPersonality_aversion_to_traffic_jam_set)
    aversion_to_construction_zone: "double" = property(_bindings.CarPersonality_aversion_to_construction_zone_get, _bindings.CarPersonality_aversion_to_construction_zone_set)
    aversion_to_traffic_light: "double" = property(_bindings.CarPersonality_aversion_to_traffic_light_get, _bindings.CarPersonality_aversion_to_traffic_light_set)
    aversion_to_lane_change: "double" = property(_bindings.CarPersonality_aversion_to_lane_change_get, _bindings.CarPersonality_aversion_to_lane_change_set)
    average_speed_offset: "MetersPerSecond" = property(_bindings.CarPersonality_average_speed_offset_get, _bindings.CarPersonality_average_speed_offset_set)
    min_speed_offset: "MetersPerSecond" = property(_bindings.CarPersonality_min_speed_offset_get, _bindings.CarPersonality_min_speed_offset_set)
    max_speed_offset: "MetersPerSecond" = property(_bindings.CarPersonality_max_speed_offset_get, _bindings.CarPersonality_max_speed_offset_set)
    acceleration_profile: "CarAccelProfile" = property(_bindings.CarPersonality_acceleration_profile_get, _bindings.CarPersonality_acceleration_profile_set)

    def __init__(self):
        _bindings.CarPersonality_swiginit(self, _bindings.new_CarPersonality())
    __swig_destroy__ = _bindings.delete_CarPersonality

# Register CarPersonality in _bindings:
_bindings.CarPersonality_swigregister(CarPersonality)

def preferences_sample_random() -> "CarPersonality":
    return _bindings.preferences_sample_random()
class Car(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    id: "CarId" = property(_bindings.Car_id_get, _bindings.Car_id_set)
    dimensions: "Dimensions" = property(_bindings.Car_dimensions_get, _bindings.Car_dimensions_set)
    capabilities: "CarCapabilities" = property(_bindings.Car_capabilities_get, _bindings.Car_capabilities_set)
    preferences: "CarPersonality" = property(_bindings.Car_preferences_get, _bindings.Car_preferences_set)
    lane_id: "LaneId" = property(_bindings.Car_lane_id_get, _bindings.Car_lane_id_set)
    lane_progress: "double" = property(_bindings.Car_lane_progress_get, _bindings.Car_lane_progress_set)
    lane_progress_meters: "Meters" = property(_bindings.Car_lane_progress_meters_get, _bindings.Car_lane_progress_meters_set)
    lane_rank: "int" = property(_bindings.Car_lane_rank_get, _bindings.Car_lane_rank_set)
    speed: "MetersPerSecond" = property(_bindings.Car_speed_get, _bindings.Car_speed_set)
    damage: "double" = property(_bindings.Car_damage_get, _bindings.Car_damage_set)
    acceleration: "MetersPerSecondSquared" = property(_bindings.Car_acceleration_get, _bindings.Car_acceleration_set)
    indicator_lane: "CarIndictor" = property(_bindings.Car_indicator_lane_get, _bindings.Car_indicator_lane_set)
    indicator_turn: "CarIndictor" = property(_bindings.Car_indicator_turn_get, _bindings.Car_indicator_turn_set)
    request_indicated_lane: "bool" = property(_bindings.Car_request_indicated_lane_get, _bindings.Car_request_indicated_lane_set)
    request_indicated_turn: "bool" = property(_bindings.Car_request_indicated_turn_get, _bindings.Car_request_indicated_turn_set)
    auto_turn_off_indicators: "bool" = property(_bindings.Car_auto_turn_off_indicators_get, _bindings.Car_auto_turn_off_indicators_set)

    def __init__(self):
        _bindings.Car_swiginit(self, _bindings.new_Car())
    __swig_destroy__ = _bindings.delete_Car

# Register Car in _bindings:
_bindings.Car_swigregister(Car)

def car_init(car: "Car", dimensions: "Vec2D", capabilities: "CarCapabilities", preferences: "CarPersonality") -> "void":
    return _bindings.car_init(car, dimensions, capabilities, preferences)

def car_get_dimensions(_self: "Car") -> "Dimensions":
    return _bindings.car_get_dimensions(_self)

def car_get_length(_self: "Car") -> "Meters":
    return _bindings.car_get_length(_self)

def car_get_width(_self: "Car") -> "Meters":
    return _bindings.car_get_width(_self)

def car_get_capabilities(_self: "Car") -> "CarCapabilities":
    return _bindings.car_get_capabilities(_self)

def car_get_preferences(_self: "Car") -> "CarPersonality":
    return _bindings.car_get_preferences(_self)

def car_get_lane_id(_self: "Car") -> "LaneId":
    return _bindings.car_get_lane_id(_self)

def car_get_lane(_self: "Car", map: "Map") -> "Lane *":
    return _bindings.car_get_lane(_self, map)

def car_get_lane_progress_meters(_self: "Car") -> "Meters":
    return _bindings.car_get_lane_progress_meters(_self)

def car_get_speed(_self: "Car") -> "MetersPerSecond":
    return _bindings.car_get_speed(_self)

def car_get_damage(_self: "Car") -> "double":
    return _bindings.car_get_damage(_self)

def car_get_acceleration(_self: "Car") -> "MetersPerSecondSquared":
    return _bindings.car_get_acceleration(_self)

def car_get_indicator_turn(_self: "Car") -> "CarIndictor":
    return _bindings.car_get_indicator_turn(_self)

def car_get_indicator_lane(_self: "Car") -> "CarIndictor":
    return _bindings.car_get_indicator_lane(_self)

def car_get_request_indicated_lane(_self: "Car") -> "bool":
    return _bindings.car_get_request_indicated_lane(_self)

def car_get_request_indicated_turn(_self: "Car") -> "bool":
    return _bindings.car_get_request_indicated_turn(_self)

def car_get_auto_turn_off_indicators(_self: "Car") -> "bool":
    return _bindings.car_get_auto_turn_off_indicators(_self)

def car_set_lane(_self: "Car", lane: "Lane") -> "void":
    return _bindings.car_set_lane(_self, lane)

def car_set_lane_progress(_self: "Car", progress: "double", progress_meters: "Meters") -> "void":
    return _bindings.car_set_lane_progress(_self, progress, progress_meters)

def car_set_speed(_self: "Car", speed: "MetersPerSecond") -> "void":
    return _bindings.car_set_speed(_self, speed)

def car_set_acceleration(_self: "Car", acceleration: "MetersPerSecondSquared") -> "void":
    return _bindings.car_set_acceleration(_self, acceleration)

def car_set_damage(_self: "Car", damage: "double const") -> "void":
    return _bindings.car_set_damage(_self, damage)

def car_set_indicator_turn(_self: "Car", indicator: "CarIndictor") -> "void":
    return _bindings.car_set_indicator_turn(_self, indicator)

def car_set_indicator_lane(_self: "Car", indicator: "CarIndictor") -> "void":
    return _bindings.car_set_indicator_lane(_self, indicator)

def car_set_request_indicated_lane(_self: "Car", request: "bool") -> "void":
    return _bindings.car_set_request_indicated_lane(_self, request)

def car_set_request_indicated_turn(_self: "Car", request: "bool") -> "void":
    return _bindings.car_set_request_indicated_turn(_self, request)

def car_set_indicator_turn_and_request(_self: "Car", indicator: "CarIndictor") -> "void":
    return _bindings.car_set_indicator_turn_and_request(_self, indicator)

def car_set_indicator_lane_and_request(_self: "Car", indicator: "CarIndictor") -> "void":
    return _bindings.car_set_indicator_lane_and_request(_self, indicator)

def car_set_auto_turn_off_indicators(_self: "Car", auto_turn_off: "bool") -> "void":
    return _bindings.car_set_auto_turn_off_indicators(_self, auto_turn_off)

def car_accel_profile_get_random_preset() -> "CarAccelProfile":
    return _bindings.car_accel_profile_get_random_preset()

def car_accel_profile_get_random_preference_preset() -> "CarAccelProfile":
    return _bindings.car_accel_profile_get_random_preference_preset()

def car_dimensions_get_random_preset() -> "Dimensions":
    return _bindings.car_dimensions_get_random_preset()

def sim_get_dt(_self: "Simulation") -> "Seconds":
    return _bindings.sim_get_dt(_self)

def sim_get_map(_self: "Simulation") -> "Map *":
    return _bindings.sim_get_map(_self)
TRAFFIC_LIGHT_GREEN = _bindings.TRAFFIC_LIGHT_GREEN
TRAFFIC_LIGHT_GREEN_YIELD = _bindings.TRAFFIC_LIGHT_GREEN_YIELD
TRAFFIC_LIGHT_YELLOW = _bindings.TRAFFIC_LIGHT_YELLOW
TRAFFIC_LIGHT_YELLOW_YIELD = _bindings.TRAFFIC_LIGHT_YELLOW_YIELD
TRAFFIC_LIGHT_RED = _bindings.TRAFFIC_LIGHT_RED
TRAFFIC_LIGHT_RED_YIELD = _bindings.TRAFFIC_LIGHT_RED_YIELD
TRAFFIC_LIGHT_STOP = _bindings.TRAFFIC_LIGHT_STOP
TRAFFIC_LIGHT_YIELD = _bindings.TRAFFIC_LIGHT_YIELD
TRAFFIC_LIGHT_NONE = _bindings.TRAFFIC_LIGHT_NONE
class BrakingDistance(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    capable: "Meters" = property(_bindings.BrakingDistance_capable_get, _bindings.BrakingDistance_capable_set)
    preferred: "Meters" = property(_bindings.BrakingDistance_preferred_get, _bindings.BrakingDistance_preferred_set)
    preferred_smooth: "Meters" = property(_bindings.BrakingDistance_preferred_smooth_get, _bindings.BrakingDistance_preferred_smooth_set)

    def __init__(self):
        _bindings.BrakingDistance_swiginit(self, _bindings.new_BrakingDistance())
    __swig_destroy__ = _bindings.delete_BrakingDistance

# Register BrakingDistance in _bindings:
_bindings.BrakingDistance_swigregister(BrakingDistance)
CAR_ACC_PROFILE_SPORTS_CAR = cvar.CAR_ACC_PROFILE_SPORTS_CAR
CAR_ACC_PROFILE_ELECTRIC_SEDAN = cvar.CAR_ACC_PROFILE_ELECTRIC_SEDAN
CAR_ACC_PROFILE_GAS_SEDAN = cvar.CAR_ACC_PROFILE_GAS_SEDAN
CAR_ACC_PROFILE_SUV = cvar.CAR_ACC_PROFILE_SUV
CAR_ACC_PROFILE_TRUCK = cvar.CAR_ACC_PROFILE_TRUCK
CAR_ACC_PROFILE_HEAVY_TRUCK = cvar.CAR_ACC_PROFILE_HEAVY_TRUCK
CAR_ACC_PREF_COMFORT = cvar.CAR_ACC_PREF_COMFORT
CAR_ACC_PREF_ECO = cvar.CAR_ACC_PREF_ECO
CAR_ACC_PREF_NORMAL = cvar.CAR_ACC_PREF_NORMAL
CAR_ACC_PREF_SPORT = cvar.CAR_ACC_PREF_SPORT
CAR_ACC_PREF_AGGRESSIVE = cvar.CAR_ACC_PREF_AGGRESSIVE
CAR_SIZE_COMPACT = cvar.CAR_SIZE_COMPACT
CAR_SIZE_TYPICAL = cvar.CAR_SIZE_TYPICAL
CAR_SIZE_MIDSIZE = cvar.CAR_SIZE_MIDSIZE
CAR_SIZE_COMPACT_SUV = cvar.CAR_SIZE_COMPACT_SUV
CAR_SIZE_LARGE_SUV = cvar.CAR_SIZE_LARGE_SUV
CAR_SIZE_FULLSIZE = cvar.CAR_SIZE_FULLSIZE
CAR_SIZE_PICKUP = cvar.CAR_SIZE_PICKUP
CAR_SIZE_BUS = cvar.CAR_SIZE_BUS

class SituationalAwareness(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    is_valid: "bool" = property(_bindings.SituationalAwareness_is_valid_get, _bindings.SituationalAwareness_is_valid_set)
    timestamp: "Seconds" = property(_bindings.SituationalAwareness_timestamp_get, _bindings.SituationalAwareness_timestamp_set)
    is_approaching_dead_end: "bool" = property(_bindings.SituationalAwareness_is_approaching_dead_end_get, _bindings.SituationalAwareness_is_approaching_dead_end_set)
    intersection: "Intersection const *" = property(_bindings.SituationalAwareness_intersection_get, _bindings.SituationalAwareness_intersection_set)
    is_on_intersection: "bool" = property(_bindings.SituationalAwareness_is_on_intersection_get, _bindings.SituationalAwareness_is_on_intersection_set)
    is_an_intersection_upcoming: "bool" = property(_bindings.SituationalAwareness_is_an_intersection_upcoming_get, _bindings.SituationalAwareness_is_an_intersection_upcoming_set)
    is_stopped_at_intersection: "bool" = property(_bindings.SituationalAwareness_is_stopped_at_intersection_get, _bindings.SituationalAwareness_is_stopped_at_intersection_set)
    road: "Road const *" = property(_bindings.SituationalAwareness_road_get, _bindings.SituationalAwareness_road_set)
    lane: "Lane const *" = property(_bindings.SituationalAwareness_lane_get, _bindings.SituationalAwareness_lane_set)
    lane_left: "Lane const *" = property(_bindings.SituationalAwareness_lane_left_get, _bindings.SituationalAwareness_lane_left_set)
    lane_right: "Lane const *" = property(_bindings.SituationalAwareness_lane_right_get, _bindings.SituationalAwareness_lane_right_set)
    distance_to_intersection: "Meters" = property(_bindings.SituationalAwareness_distance_to_intersection_get, _bindings.SituationalAwareness_distance_to_intersection_set)
    distance_to_end_of_lane: "Meters" = property(_bindings.SituationalAwareness_distance_to_end_of_lane_get, _bindings.SituationalAwareness_distance_to_end_of_lane_set)
    distance_to_end_of_lane_from_leading_edge: "Meters" = property(_bindings.SituationalAwareness_distance_to_end_of_lane_from_leading_edge_get, _bindings.SituationalAwareness_distance_to_end_of_lane_from_leading_edge_set)
    is_approaching_end_of_lane: "bool" = property(_bindings.SituationalAwareness_is_approaching_end_of_lane_get, _bindings.SituationalAwareness_is_approaching_end_of_lane_set)
    is_at_end_of_lane: "bool" = property(_bindings.SituationalAwareness_is_at_end_of_lane_get, _bindings.SituationalAwareness_is_at_end_of_lane_set)
    is_on_leftmost_lane: "bool" = property(_bindings.SituationalAwareness_is_on_leftmost_lane_get, _bindings.SituationalAwareness_is_on_leftmost_lane_set)
    is_on_rightmost_lane: "bool" = property(_bindings.SituationalAwareness_is_on_rightmost_lane_get, _bindings.SituationalAwareness_is_on_rightmost_lane_set)
    lane_progress: "double" = property(_bindings.SituationalAwareness_lane_progress_get, _bindings.SituationalAwareness_lane_progress_set)
    lane_progress_m: "Meters" = property(_bindings.SituationalAwareness_lane_progress_m_get, _bindings.SituationalAwareness_lane_progress_m_set)
    is_turn_possible: "bool [3]" = property(_bindings.SituationalAwareness_is_turn_possible_get, _bindings.SituationalAwareness_is_turn_possible_set)
    light_for_turn: "TrafficLight [3]" = property(_bindings.SituationalAwareness_light_for_turn_get, _bindings.SituationalAwareness_light_for_turn_set)
    lane_next_after_turn: "Lane const *[3]" = property(_bindings.SituationalAwareness_lane_next_after_turn_get, _bindings.SituationalAwareness_lane_next_after_turn_set)
    is_lane_change_left_possible: "bool" = property(_bindings.SituationalAwareness_is_lane_change_left_possible_get, _bindings.SituationalAwareness_is_lane_change_left_possible_set)
    is_lane_change_right_possible: "bool" = property(_bindings.SituationalAwareness_is_lane_change_right_possible_get, _bindings.SituationalAwareness_is_lane_change_right_possible_set)
    is_merge_possible: "bool" = property(_bindings.SituationalAwareness_is_merge_possible_get, _bindings.SituationalAwareness_is_merge_possible_set)
    is_exit_possible: "bool" = property(_bindings.SituationalAwareness_is_exit_possible_get, _bindings.SituationalAwareness_is_exit_possible_set)
    is_on_entry_ramp: "bool" = property(_bindings.SituationalAwareness_is_on_entry_ramp_get, _bindings.SituationalAwareness_is_on_entry_ramp_set)
    is_exit_available: "bool" = property(_bindings.SituationalAwareness_is_exit_available_get, _bindings.SituationalAwareness_is_exit_available_set)
    is_exit_available_eventually: "bool" = property(_bindings.SituationalAwareness_is_exit_available_eventually_get, _bindings.SituationalAwareness_is_exit_available_eventually_set)
    merges_into_lane: "Lane const *" = property(_bindings.SituationalAwareness_merges_into_lane_get, _bindings.SituationalAwareness_merges_into_lane_set)
    exit_lane: "Lane const *" = property(_bindings.SituationalAwareness_exit_lane_get, _bindings.SituationalAwareness_exit_lane_set)
    lane_target_for_indicator: "Lane const *[3]" = property(_bindings.SituationalAwareness_lane_target_for_indicator_get, _bindings.SituationalAwareness_lane_target_for_indicator_set)
    is_vehicle_ahead: "bool" = property(_bindings.SituationalAwareness_is_vehicle_ahead_get, _bindings.SituationalAwareness_is_vehicle_ahead_set)
    is_vehicle_behind: "bool" = property(_bindings.SituationalAwareness_is_vehicle_behind_get, _bindings.SituationalAwareness_is_vehicle_behind_set)
    lead_vehicle: "Car const *" = property(_bindings.SituationalAwareness_lead_vehicle_get, _bindings.SituationalAwareness_lead_vehicle_set)
    following_vehicle: "Car const *" = property(_bindings.SituationalAwareness_following_vehicle_get, _bindings.SituationalAwareness_following_vehicle_set)
    distance_to_lead_vehicle: "Meters" = property(_bindings.SituationalAwareness_distance_to_lead_vehicle_get, _bindings.SituationalAwareness_distance_to_lead_vehicle_set)
    distance_to_following_vehicle: "Meters" = property(_bindings.SituationalAwareness_distance_to_following_vehicle_get, _bindings.SituationalAwareness_distance_to_following_vehicle_set)
    braking_distance: "BrakingDistance" = property(_bindings.SituationalAwareness_braking_distance_get, _bindings.SituationalAwareness_braking_distance_set)
    slowest_speed_yet_on_current_lane: "MetersPerSecond" = property(_bindings.SituationalAwareness_slowest_speed_yet_on_current_lane_get, _bindings.SituationalAwareness_slowest_speed_yet_on_current_lane_set)
    slowest_speed_position: "Meters" = property(_bindings.SituationalAwareness_slowest_speed_position_get, _bindings.SituationalAwareness_slowest_speed_position_set)
    slowest_speed_yet_at_end_of_lane: "MetersPerSecond" = property(_bindings.SituationalAwareness_slowest_speed_yet_at_end_of_lane_get, _bindings.SituationalAwareness_slowest_speed_yet_at_end_of_lane_set)
    full_stopped_yet_at_end_of_lane: "bool" = property(_bindings.SituationalAwareness_full_stopped_yet_at_end_of_lane_get, _bindings.SituationalAwareness_full_stopped_yet_at_end_of_lane_set)
    rolling_stopped_yet_at_end_of_lane: "bool" = property(_bindings.SituationalAwareness_rolling_stopped_yet_at_end_of_lane_get, _bindings.SituationalAwareness_rolling_stopped_yet_at_end_of_lane_set)

    def __init__(self):
        _bindings.SituationalAwareness_swiginit(self, _bindings.new_SituationalAwareness())
    __swig_destroy__ = _bindings.delete_SituationalAwareness

# Register SituationalAwareness in _bindings:
_bindings.SituationalAwareness_swigregister(SituationalAwareness)

def sim_get_time(_self: "Simulation") -> "Seconds":
    return _bindings.sim_get_time(_self)

def sim_get_situational_awareness(_self: "Simulation", id: "CarId") -> "SituationalAwareness *":
    return _bindings.sim_get_situational_awareness(_self, id)

def situational_awareness_build(sim: "Simulation", car_id: "CarId") -> "void":
    return _bindings.situational_awareness_build(sim, car_id)

def npc_car_make_decisions(_self: "Car", sim: "Simulation") -> "void":
    return _bindings.npc_car_make_decisions(_self, sim)

def turn_sample_possible(situation: "SituationalAwareness") -> "CarIndictor":
    return _bindings.turn_sample_possible(situation)

def lane_change_sample_possible(situation: "SituationalAwareness") -> "CarIndictor":
    return _bindings.lane_change_sample_possible(situation)

def car_is_lane_change_dangerous(car: "Car", sim: "Simulation", situation: "SituationalAwareness", lane_change_indicator: "CarIndictor") -> "bool":
    return _bindings.car_is_lane_change_dangerous(car, sim, situation, lane_change_indicator)

def car_compute_acceleration_chase_target(car: "Car", position_target: "Meters", speed_target: "MetersPerSecond", position_target_overshoot_buffer: "Meters", speed_limit: "MetersPerSecond") -> "MetersPerSecondSquared":
    return _bindings.car_compute_acceleration_chase_target(car, position_target, speed_target, position_target_overshoot_buffer, speed_limit)

def car_compute_acceleration_adjust_speed(car: "Car", speed_target: "MetersPerSecond", use_preferred_accel_profile: "bool") -> "MetersPerSecondSquared":
    return _bindings.car_compute_acceleration_adjust_speed(car, speed_target, use_preferred_accel_profile)

def car_compute_acceleration_cruise(car: "Car", speed_target: "MetersPerSecond") -> "MetersPerSecondSquared":
    return _bindings.car_compute_acceleration_cruise(car, speed_target)

def car_compute_acceleration_stop(car: "Car", use_preferred_accel_profile: "bool") -> "MetersPerSecondSquared":
    return _bindings.car_compute_acceleration_stop(car, use_preferred_accel_profile)

def car_compute_acceleration_stop_max_brake(car: "Car", use_preferred_accel_profile: "bool") -> "MetersPerSecondSquared":
    return _bindings.car_compute_acceleration_stop_max_brake(car, use_preferred_accel_profile)

def car_compute_braking_distance(car: "Car") -> "BrakingDistance":
    return _bindings.car_compute_braking_distance(car)

def car_should_yield_at_intersection(car: "Car", sim: "Simulation", situation: "SituationalAwareness", turn_indicator: "CarIndictor") -> "bool":
    return _bindings.car_should_yield_at_intersection(car, sim, situation, turn_indicator)
class ControlError(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    position: "Meters" = property(_bindings.ControlError_position_get, _bindings.ControlError_position_set)
    speed: "MetersPerSecond" = property(_bindings.ControlError_speed_get, _bindings.ControlError_speed_set)

    def __init__(self):
        _bindings.ControlError_swiginit(self, _bindings.new_ControlError())
    __swig_destroy__ = _bindings.delete_ControlError

# Register ControlError in _bindings:
_bindings.ControlError_swigregister(ControlError)

def control_compute_pd_accel(error: "ControlError", k: "double") -> "MetersPerSecondSquared":
    return _bindings.control_compute_pd_accel(error, k)

def control_speed_compute_pd_accel(error: "ControlError", k: "double") -> "MetersPerSecondSquared":
    return _bindings.control_speed_compute_pd_accel(error, k)

def control_compute_const_accel(error: "ControlError") -> "MetersPerSecondSquared":
    return _bindings.control_compute_const_accel(error)

def control_compute_bounded_accel(error: "ControlError", max_accel: "MetersPerSecondSquared", max_speed: "MetersPerSecond") -> "MetersPerSecondSquared":
    return _bindings.control_compute_bounded_accel(error, max_accel, max_speed)

def control_speed_compute_bounded_accel(error: "ControlError", max_accel: "MetersPerSecondSquared", max_speed: "MetersPerSecond") -> "MetersPerSecondSquared":
    return _bindings.control_speed_compute_bounded_accel(error, max_accel, max_speed)

def left_turn(_self: "Car", sim: "Simulation") -> "bool":
    r""" Execute a left-turn through an intersection."""
    return _bindings.left_turn(_self, sim)

def right_turn(_self: "Car", sim: "Simulation") -> "bool":
    r""" Execute a right-turn through an intersection."""
    return _bindings.right_turn(_self, sim)

def merge(_self: "Car", sim: "Simulation", direction: "char const *", duration: "double") -> "bool":
    r"""
    Initiate or continue a lane-merge manoeuvre.

    :type direction: string
    :param direction:  "left", "l", "right", or "r" (case-insensitive).
    :type duration: float
    :param duration:   Hard time-out (seconds) before the merge aborts.
    """
    return _bindings.merge(_self, sim, direction, duration)

def pass_vehicle(_self: "Car", sim: "Simulation", target: "Car", should_merge: "bool", merge_buffer: "Meters", speed_buffer: "MetersPerSecond", duration: "double") -> "bool":
    r"""
    Pass a slower vehicle and (optionally) merge back.

    :type target: :py:class:`Car`
    :param target:         Vehicle to overtake.
    :type should_merge: boolean
    :param should_merge:   Merge back into the original lane afterwards?
    :type merge_buffer: float
    :param merge_buffer:   Longitudinal gap to leave before merging back (m).
    :type speed_buffer: float
    :param speed_buffer:   Extra speed relative to ``target`` while passing (m/s).
    :type duration: float
    :param duration:       Hard time-out (seconds) for the entire manoeuvre.
    """
    return _bindings.pass_vehicle(_self, sim, target, should_merge, merge_buffer, speed_buffer, duration)

def cruise(_self: "Car", target_speed: "float") -> "bool":
    r"""
    Cruise toward a target speed.

    Returns `true` once the ego vehicle is within ±1 mph of the target.
    """
    return _bindings.cruise(_self, target_speed)

def cruise_continue(_self: "Car", sim: "Simulation", duration: "double") -> "bool":
    r"""
    Maintain current speed for a fixed duration (no-op helper).

    Useful for stitching actions in behaviour scripts.
    """
    return _bindings.cruise_continue(_self, sim, duration)
MAX_CARS_IN_SIMULATION = _bindings.MAX_CARS_IN_SIMULATION
MAX_NUM_HAZARDS_EACH_TYPE = _bindings.MAX_NUM_HAZARDS_EACH_TYPE
MORNING_START = _bindings.MORNING_START
AFTERNOON_START = _bindings.AFTERNOON_START
EVENING_START = _bindings.EVENING_START
NIGHT_START = _bindings.NIGHT_START
MONDAY = _bindings.MONDAY
TUESDAY = _bindings.TUESDAY
WEDNESDAY = _bindings.WEDNESDAY
THURSDAY = _bindings.THURSDAY
FRIDAY = _bindings.FRIDAY
SATURDAY = _bindings.SATURDAY
SUNDAY = _bindings.SUNDAY
class ClockReading(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    days: "Days" = property(_bindings.ClockReading_days_get, _bindings.ClockReading_days_set)
    hours: "Hours" = property(_bindings.ClockReading_hours_get, _bindings.ClockReading_hours_set)
    minutes: "Minutes" = property(_bindings.ClockReading_minutes_get, _bindings.ClockReading_minutes_set)
    seconds: "Seconds" = property(_bindings.ClockReading_seconds_get, _bindings.ClockReading_seconds_set)
    day_of_week: "DayOfWeek" = property(_bindings.ClockReading_day_of_week_get, _bindings.ClockReading_day_of_week_set)

    def __init__(self):
        _bindings.ClockReading_swiginit(self, _bindings.new_ClockReading())
    __swig_destroy__ = _bindings.delete_ClockReading

# Register ClockReading in _bindings:
_bindings.ClockReading_swigregister(ClockReading)

def clock_reading(days: "Days const", hours: "Hours const", minutes: "Minutes const", seconds: "Seconds const") -> "ClockReading":
    return _bindings.clock_reading(days, hours, minutes, seconds)

def clock_reading_from_seconds(seconds: "Seconds const") -> "ClockReading":
    return _bindings.clock_reading_from_seconds(seconds)

def clock_reading_to_seconds(clock: "ClockReading") -> "Seconds":
    return _bindings.clock_reading_to_seconds(clock)

def clock_reading_add(clock1: "ClockReading", clock2: "ClockReading") -> "ClockReading":
    return _bindings.clock_reading_add(clock1, clock2)

def clock_reading_add_seconds(clock: "ClockReading", seconds: "Seconds const") -> "ClockReading":
    return _bindings.clock_reading_add_seconds(clock, seconds)
WEATHER_SUNNY = _bindings.WEATHER_SUNNY
WEATHER_CLOUDY = _bindings.WEATHER_CLOUDY
WEATHER_RAINY = _bindings.WEATHER_RAINY
WEATHER_FOGGY = _bindings.WEATHER_FOGGY
WEATHER_SNOWY = _bindings.WEATHER_SNOWY
class Simulation(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    map: "Map" = property(_bindings.Simulation_map_get, _bindings.Simulation_map_set)
    initial_clock_reading: "ClockReading" = property(_bindings.Simulation_initial_clock_reading_get, _bindings.Simulation_initial_clock_reading_set)
    cars: "Car [1024]" = property(_bindings.Simulation_cars_get, _bindings.Simulation_cars_set)
    situational_awarenesses: "SituationalAwareness [1024]" = property(_bindings.Simulation_situational_awarenesses_get, _bindings.Simulation_situational_awarenesses_set)
    num_cars: "int" = property(_bindings.Simulation_num_cars_get, _bindings.Simulation_num_cars_set)
    time: "Seconds" = property(_bindings.Simulation_time_get, _bindings.Simulation_time_set)
    dt: "Seconds" = property(_bindings.Simulation_dt_get, _bindings.Simulation_dt_set)
    weather: "Weather" = property(_bindings.Simulation_weather_get, _bindings.Simulation_weather_set)
    is_agent_enabled: "bool" = property(_bindings.Simulation_is_agent_enabled_get, _bindings.Simulation_is_agent_enabled_set)
    is_synchronized: "bool" = property(_bindings.Simulation_is_synchronized_get, _bindings.Simulation_is_synchronized_set)
    is_paused: "bool" = property(_bindings.Simulation_is_paused_get, _bindings.Simulation_is_paused_set)
    simulation_speedup: "double" = property(_bindings.Simulation_simulation_speedup_get, _bindings.Simulation_simulation_speedup_set)
    should_quit_when_rendering_window_closed: "bool" = property(_bindings.Simulation_should_quit_when_rendering_window_closed_get, _bindings.Simulation_should_quit_when_rendering_window_closed_set)
    render_socket: "int" = property(_bindings.Simulation_render_socket_get, _bindings.Simulation_render_socket_set)
    is_connected_to_render_server: "bool" = property(_bindings.Simulation_is_connected_to_render_server_get, _bindings.Simulation_is_connected_to_render_server_set)

    def __init__(self):
        _bindings.Simulation_swiginit(self, _bindings.new_Simulation())
    __swig_destroy__ = _bindings.delete_Simulation

# Register Simulation in _bindings:
_bindings.Simulation_swigregister(Simulation)

def sim_malloc() -> "Simulation *":
    return _bindings.sim_malloc()

def sim_free(_self: "Simulation") -> "void":
    return _bindings.sim_free(_self)

def sim_init(sim: "Simulation") -> "void":
    return _bindings.sim_init(sim)

def sim_get_new_car(_self: "Simulation") -> "Car *":
    return _bindings.sim_get_new_car(_self)

def sim_connect_to_render_server(_self: "Simulation", server_ip: "char const *", port: "int") -> "bool":
    return _bindings.sim_connect_to_render_server(_self, server_ip, port)

def sim_disconnect_from_render_server(_self: "Simulation") -> "void":
    return _bindings.sim_disconnect_from_render_server(_self)
COMMAND_NONE = _bindings.COMMAND_NONE
COMMAND_QUIT = _bindings.COMMAND_QUIT
COMMAND_SIM_INCREASE_SPEED = _bindings.COMMAND_SIM_INCREASE_SPEED
COMMAND_SIM_DECREASE_SPEED = _bindings.COMMAND_SIM_DECREASE_SPEED
COMMAND_SIM_PAUSE = _bindings.COMMAND_SIM_PAUSE

def sim_get_initial_clock_reading(_self: "Simulation") -> "ClockReading":
    return _bindings.sim_get_initial_clock_reading(_self)

def sim_get_num_cars(_self: "Simulation") -> "int":
    return _bindings.sim_get_num_cars(_self)

def sim_get_weather(_self: "Simulation") -> "Weather":
    return _bindings.sim_get_weather(_self)

def sim_get_clock_reading(_self: "Simulation") -> "ClockReading":
    return _bindings.sim_get_clock_reading(_self)

def sim_get_day_of_week(_self: "Simulation") -> "DayOfWeek":
    return _bindings.sim_get_day_of_week(_self)

def sim_is_agent_enabled(_self: "Simulation") -> "bool":
    return _bindings.sim_is_agent_enabled(_self)

def sim_get_agent_car(_self: "Simulation") -> "Car *":
    return _bindings.sim_get_agent_car(_self)

def sim_set_dt(_self: "Simulation", dt: "Seconds") -> "void":
    return _bindings.sim_set_dt(_self, dt)

def sim_set_initial_clock_reading(_self: "Simulation", clock: "ClockReading") -> "void":
    return _bindings.sim_set_initial_clock_reading(_self, clock)

def sim_set_weather(_self: "Simulation", weather: "Weather") -> "void":
    return _bindings.sim_set_weather(_self, weather)

def sim_set_agent_enabled(_self: "Simulation", enabled: "bool") -> "void":
    return _bindings.sim_set_agent_enabled(_self, enabled)

def sim_set_synchronized(_self: "Simulation", is_synchronized: "bool", simulation_speedup: "double") -> "void":
    return _bindings.sim_set_synchronized(_self, is_synchronized, simulation_speedup)

def sim_set_should_quit_when_rendering_window_closed(_self: "Simulation", should_quit: "bool") -> "void":
    return _bindings.sim_set_should_quit_when_rendering_window_closed(_self, should_quit)

def sim_is_weekend(_self: "Simulation") -> "bool":
    return _bindings.sim_is_weekend(_self)

def sim_is_morning(_self: "Simulation") -> "bool":
    return _bindings.sim_is_morning(_self)

def sim_is_afternoon(_self: "Simulation") -> "bool":
    return _bindings.sim_is_afternoon(_self)

def sim_is_evening(_self: "Simulation") -> "bool":
    return _bindings.sim_is_evening(_self)

def sim_is_night(_self: "Simulation") -> "bool":
    return _bindings.sim_is_night(_self)

def sunlight_intensity(_self: "Simulation") -> "double":
    return _bindings.sunlight_intensity(_self)

def sim_integrate(_self: "Simulation", sim_duration: "Seconds") -> "void":
    return _bindings.sim_integrate(_self, sim_duration)

def simulate(_self: "Simulation", sim_duration: "Seconds") -> "void":
    return _bindings.simulate(_self, sim_duration)

def sim_step(_self: "Simulation") -> "void":
    return _bindings.sim_step(_self)
class TrackIntersectionPoint(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    lane1: "Lane const *" = property(_bindings.TrackIntersectionPoint_lane1_get, _bindings.TrackIntersectionPoint_lane1_set)
    lane2: "Lane const *" = property(_bindings.TrackIntersectionPoint_lane2_get, _bindings.TrackIntersectionPoint_lane2_set)
    progress1: "double" = property(_bindings.TrackIntersectionPoint_progress1_get, _bindings.TrackIntersectionPoint_progress1_set)
    progress2: "double" = property(_bindings.TrackIntersectionPoint_progress2_get, _bindings.TrackIntersectionPoint_progress2_set)
    exists: "bool" = property(_bindings.TrackIntersectionPoint_exists_get, _bindings.TrackIntersectionPoint_exists_set)

    def __init__(self):
        _bindings.TrackIntersectionPoint_swiginit(self, _bindings.new_TrackIntersectionPoint())
    __swig_destroy__ = _bindings.delete_TrackIntersectionPoint

# Register TrackIntersectionPoint in _bindings:
_bindings.TrackIntersectionPoint_swigregister(TrackIntersectionPoint)

def awesim_map_setup(map: "Map", city_width: "Meters") -> "void":
    return _bindings.awesim_map_setup(map, city_width)

def awesim_setup(sim: "Simulation", city_width: "Meters", num_cars: "int", dt: "Seconds", initial_clock_reading: "ClockReading", weather: "Weather") -> "void":
    return _bindings.awesim_setup(sim, city_width, num_cars, dt, initial_clock_reading, weather)

